#!/usr/bin/env ruby

program = $stdin.readlines.join("\n")
program.gsub!('!', 'puts ')
program.gsub!('?', "if 0 == ")
program.gsub!('{', ';')
program.gsub!('}', ';end;')
$stderr.puts program
eval(program)
